use test;

create table country(
	country_id int primary key auto_increment,
    country_name varchar(255) not null,
    created_at timestamp default current_timestamp
);
insert into country (country_name) 
values('India'),('United States'),('Canada'),('United Kingdom'),('Australia'),('Germany'),('France'),('China'),
('Japan'),('Brazil'),('South Africa'),('Russia'),('Mexico'),('Italy'),('Spain'),('Netherlands'),
('Singapore'),('United Arab Emirates'),('Saudi Arabia'),('Turkey'),('Indonesia'),('South Korea'),('Argentina')
,('Nigeria');

select * from country;

create table state(
	state_id int primary key auto_increment,
    country_id int ,
    state_name varchar(255) not null,
    created_at timestamp default current_timestamp,
    foreign key (country_id) references country(country_id)
);
insert into state(country_id,state_name)
values(1,'gujarat'),
(1,'Maharashtra'),
(1,'Karnataka'),
(1,'Tamil Nadu'),
(1,'Delhi'),
(2,'California'),
(2,'Texas'),
(2,'New York'),
(2,'Florida'),
(2,'Illinois'),
(3,'Ontario'),
(3,'Quebec'),
(3,'British Columbia'),
(3,'Alberta'),
(4,'England'),
(4,'Scotland'),
(4,'Wales'),
(4,'Northern Ireland'),
(5,'New South Wales'),
(5,'Victoria'),
(5,'Queensland'),
(5,'Western Australia'),
(6,'Bavaria'),
(6,'North Rhine-Westphalia'),
(6,'Berlin'),
(7,'Île-de-France'),
(7,'Provence-Alpes-Côte d’Azur'),
(7,'Auvergne-Rhône-Alpes'),
(8,'Guangdong'),
(8,'Beijing'),
(8,'Shanghai'),
(8,'Sichuan'),
(9,'Tokyo'),
(9,'Osaka'),
(9,'Kanagawa'),
(9,'Aichi'),
(10,'São Paulo'),
(10,'Rio de Janeiro'),
(10,'Minas Gerais'),
(11,'Gauteng'),
(11,'Western Cape'),
(11,'KwaZulu-Natal'),
(12,'Moscow'),
(12,'Saint Petersburg'),
(12,'Novosibirsk'),
(13,'Mexico City'),
(13,'Jalisco'),
(13,'Nuevo León'),
(14,'Lombardy'),
(14,'Lazio'),
(14,'Campania'),
(15,'Madrid'),
(15,'Catalonia'),
(15,'Andalusia'),
(16,'North Holland'),
(16,'South Holland'),
(16,'Utrecht'),
(17,'Singapore'),
(18,'Dubai'),
(18,'Abu Dhabi'),
(18,'Sharjah'),
(19,'Riyadh'),
(19,'Makkah'),
(19,'Eastern Province'),
(20,'Istanbul'),
(20,'Ankara'),
(20,'Izmir'),
(21,'Jakarta'),
(21,'West Java'),
(21,'East Java'),
(22,'Seoul'),
(22,'Busan'),
(22,'Incheon'),
(23,'Buenos Aires'),
(23,'Córdoba'),
(23,'Santa Fe'),
(24,'Lagos'),
(24,'Abuja'),
(24,'Kano');

select * from state;

create table city(
	city_id int primary key auto_increment,
    state_id int,
    city_name varchar(255) not null,
    created_at timestamp default current_timestamp,
    foreign key (state_id) references state(state_id)
   
);
insert into city(state_id,city_name)
values(1,'Ahmedabad'),
(1,'surat'),
(1,'vadodara'),
(2,'mumbai'),
(2,'pune'),
(2,'nagpur'),
(3,'Bangalore'),
(3,'mysore'),
(4,'chennai'),
(4,'Coimbatore'),
(5,'new delhi'),
(6,'Los Angeles'),
(6,'San Francisco'),
(6,'San Diego'),
(7,'Houston'),
(7,'Dallas'),
(7,'Austin'),
(8,'New York City'),
(9,'Miami'),
(9,'Orlando'),
(10,'Chicago'),
(11,'Toronto'),
(11,'Ottawa'),
(12,'Montreal'),
(12,'Quebec City'),
(13,'Vancouver'),
(14,'Calgary'),
(14,'Edmonton'),
(15,'London'),
(15,'Manchester'),
(15,'Birmingham'),
(16,'Edinburgh'),
(16,'Glasgow'),
(17,'Cardiff'),
(18,'Belfast'),
(19,'Sydney'),
(20,'Melbourne'),
(21,'Brisbane'),
(22,'Perth'),
(23,'Munich'),
(23,'Nuremberg'),
(24,'Cologne'),
(24,'Düsseldorf'),
(25,'Berlin'),
(26,'Paris'),
(27,'Marseille'),
(27,'Nice'),
(28,'Lyon'),
(29,'Guangzhou'),
(29,'Shenzhen'),
(30,'Beijing'),
(31,'Shanghai'),
(32,'Chengdu'),
(33,'Tokyo'),
(34,'Osaka'),
(35,'Yokohama'),
(36,'Nagoya'),
(37,'São Paulo'),
(38,'Rio de Janeiro'),
(39,'Belo Horizonte'),
(40,'Johannesburg'),
(40,'Pretoria'),
(41,'Cape Town'),
(42,'Durban'),
(43,'Moscow'),
(44,'Saint Petersburg'),
(45,'Novosibirsk'),
(46,'Mexico City'),
(47,'Guadalajara'),
(48,'Monterrey'),
(49,'Milan'),
(50,'Rome'),
(51,'Naples'),
(52,'Madrid'),
(53,'Barcelona'),
(54,'Seville'),
(55,'Amsterdam'),
(56,'Rotterdam'),
(57,'Utrecht'),
(58,'Singapore'),
(59,'Dubai'),
(60,'Abu Dhabi'),
(61,'Sharjah'),
(62,'Riyadh'),
(63,'Mecca'),
(64,'Dammam'),
(65,'Istanbul'),
(66,'Ankara'),
(67,'Izmir'),
(68,'Jakarta'),
(69,'Bandung'),
(70,'Surabaya'),
(71,'Seoul'),
(72,'Busan'),
(73,'Incheon'),
(74,'Buenos Aires'),
(75,'Córdoba'),
(76,'Rosario'),
(77,'Lagos'),
(78,'Abuja'),
(79,'Kano');






